apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bv-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iDqrks/BV_Milestone2.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: bv-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
